name: windows-build

on: [push]

env:
  cpp: ./PITemp/*.vcxproj
  cs: ./PITempCS/*.vcxproj
  dir: .

jobs:
  cpp:
    strategy:
      matrix:
        arch: ["x64", "x86"]
        
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: run msbuild
      run: msbuild ${{ env.cpp }} -p:Platform="${{ matrix.arch }}" -p:Configuration=Release -m
      
    - name: check dir
      run: |
        tree

    - name: collect staging built files
      run: mv build/Release/atsplugin.dll atsplugin_${{ matrix.arch }}.dll

    - name: upload built files
      uses: actions/upload-artifact@v3
      with:
        name: built
        path: atsplugin_${{ matrix.arch }}.dll

  cs:
    strategy:
      matrix:
        arch: ["x64", "x86"]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x86
      
    - name: setup DllExport
      run: |
        Start-BitsTransfer -Source https://github.com/3F/DllExport/releases/download/v1.7.4/DllExport.bat
        ./DllExport -action Export 
    
    - name: run msbuild
      run: msbuild BVE_ATSPITemp.sln -p:Platform="${{ matrix.arch }}" -p:Configuration=Release -m
      
    - name: check dir
      run: |
        tree

    - name: collect staging built files
      run: mv build/Release/atsplugin.dll atsplugin_${{ matrix.arch }}.dll

    - name: upload built files
      uses: actions/upload-artifact@v3
      with:
        name: built
        path: atsplugin_${{ matrix.arch }}.dll
